# Generated by Django 5.0.6 on 2024-05-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('is_bot', models.BooleanField(null=True)),
                ('is_premium', models.BooleanField(null=True)),
                ('language_code', models.CharField(max_length=10, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=255, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_support', models.BooleanField(default=False)),
            ],
        ),
    ]
