# Generated by Django 5.0.6 on 2024-05-09 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_blocked',
            new_name='is_banned',
        ),
    ]
