# Generated by Django 5.0.6 on 2024-05-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0002_rename_is_blocked_user_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_added',
            field=models.BigIntegerField(null=True),
        ),
    ]
