# Generated by Django 5.0.6 on 2024-05-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0005_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
