# Generated by Django 5.0.6 on 2024-05-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0006_systemtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
