# Generated by Django 5.0.6 on 2024-05-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0008_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
